# Generated by Django 5.0.1 on 2024-02-29 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_event_date_time_event_date_event_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rsvps',
            field=models.ManyToManyField(blank=True, related_name='rsvps', to=settings.AUTH_USER_MODEL),
        ),
    ]
