# Generated by Django 5.0.1 on 2024-03-06 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rsvp_events',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
