# Generated by Django 5.0.1 on 2024-03-07 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_profile_rsvp_events_delete_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.profile'),
        ),
    ]
